### ISSUE TITLE
http://wewantjs.org/ hacked?

### ISSUE THREAD

**Issue by joshterrill** [ozten/TLD.js#44]
Has anyone went to http://wewantjs.org/ lately?

**Comment by ozten** [comment]
I let the domain lapse, as the 2 blocker bugs are pretty significant.

I'll remove the references to wewantjs.org from the repo. Thanks!

**Comment by vvo** [comment]
there's still a reference in the project description (github)

**Comment by ozten** [comment]
Fixed.
